const babel = require('@babel/core');
// babel实例的结构
console.log(babel);
// 	 Plugin: [Function: Plugin],
//   File: [Getter],
//   buildExternalHelpers: [Getter],
//   resolvePlugin: [Getter],
//   resolvePreset: [Getter],
//   version: [Getter],
//   getEnv: [Getter],
//   traverse: [Getter],
//   template: [Getter],
//   createConfigItem: [Getter],
//   loadPartialConfig: [Getter],
//   loadOptions: [Getter],
//   transform: [Getter],
//   transformSync: [Getter],
//   transformAsync: [Getter],
//   transformFile: [Getter],
//   transformFileSync: [Getter],
//   transformFileAsync: [Getter],
//   transformFromAst: [Getter],
//   transformFromAstSync: [Getter],
//   transformFromAstAsync: [Getter],
//   parse: [Getter],
//   parseSync: [Getter],
//   parseAsync: [Getter],
//   DEFAULT_EXTENSIONS: [ '.js', '.jsx', '.es6', '.es', '.mjs' ],
//   OptionManager: [Function: OptionManager],
//   types: [Getter] }